# Generated by Django 3.2.5 on 2023-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
